#!/bin/bash
#
# start/stop NRTS processes
#

case $1 in
start)

    NRTSRC=~nrts/etc/start/boot.tcsh
    if [ -f ${NRTSRC} ]; then
        echo "Starting NRTS"
        csh ${NRTSRC} > /dev/null &
    fi
    ;;
        
stop)
    echo "Stopping NRTS"
    pkill -TERM -x isid
    pkill -TERM -x isidl
    pkill -TERM -x i10dld
    pkill -TERM -x isi330
    pkill -TERM -x nrts_edes
    pkill -TERM -x qhlp
    pkill -TERM -x tristar10
    pkill -TERM -x paro10
    pkill -TERM -x sbds
    sleep 2
    pkill -TERM -x ringserver
    ;;
*)
    echo "Usage: ~nrts/etc/init.d/nrts { start | stop }"
    ;;
esac
